spring.application.name=PrimeMobile

# =====================================================
# DATABASE CONFIGURATION (SQL SERVER)
# =====================================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PrimeMobile;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# =====================================================
# JPA / HIBERNATE CONFIGURATION
# =====================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Lưu ý: Chiến lược này giữ nguyên tên thuộc tính Java làm tên cột DB (Cần dùng @Column rõ ràng nếu DB dùng snake_case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# =====================================================
# GIAO HANG NHANH (GHN) API CONFIGURATION
# =====================================================
ghn.api.url=https://online-gateway.ghn.vn/shiip/public-api
ghn.api.token=f85e8a9f-6de5-11f1-ad95-a62736c4c553
ghn.api.shop-id=6504977
ghn.api.from-district-id=3440

# =====================================================
# VNPAY SANDBOX CONFIGURATION
# =====================================================
vnpay.tmn-code=BAHQV3WM
vnpay.secret-key=AB8H9D081ZRV6JCFEMZH9K15Q47SZNJ9
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# URL browser
vnpay.return-url=http://localhost:8080/api/vnpay/vnpay-return

# URL VNPay
# Khi deploy production:
vnpay.ipn-url=http://localhost:8080/api/vnpay/ipn